version: '3.8'

services:
  cubejs:
    image: cubejs/cube:latest
    environment:
      CUBEJS_DEV_MODE: false
      
      # Primary PostgreSQL Database (Sales Data)
      CUBEJS_DB_TYPE: postgres
      CUBEJS_DB_HOST: ${CUBEJS_DB_HOST}
      CUBEJS_DB_NAME: ${CUBEJS_DB_NAME:-analyticsdb}
      CUBEJS_DB_USER: ${CUBEJS_DB_USER:-postgres}
      CUBEJS_DB_PASS: ${CUBEJS_DB_PASS}
      CUBEJS_DB_PORT: ${CUBEJS_DB_PORT:-5432}
      
      # Marketing schema in same PostgreSQL database
      CUBEJS_DATASOURCES: default,marketing
      CUBEJS_DS_MARKETING_DB_TYPE: postgres
      CUBEJS_DS_MARKETING_DB_HOST: ${CUBEJS_DB_HOST}
      CUBEJS_DS_MARKETING_DB_NAME: ${CUBEJS_DB_NAME:-analyticsdb}
      CUBEJS_DS_MARKETING_DB_USER: ${CUBEJS_DB_USER:-postgres}
      CUBEJS_DS_MARKETING_DB_PASS: ${CUBEJS_DB_PASS}
      CUBEJS_DS_MARKETING_DB_PORT: ${CUBEJS_DB_PORT:-5432}
      CUBEJS_DS_MARKETING_DB_SCHEMA: marketing
      
      # Cube.js Configuration
      CUBEJS_API_SECRET: ${CUBEJS_API_SECRET}
      CUBEJS_EXTERNAL_DEFAULT: true
      CUBEJS_SCHEDULED_REFRESH_DEFAULT: true
      
      # Render specific settings
      PORT: ${PORT:-4000}
      
    volumes:
      - ./cube:/cube/conf
    ports:
      - "${PORT:-4000}:4000"
    restart: unless-stopped