// 📊 PowerBI Advanced Editor M Code - Ready to Copy & Paste
// Choose the query you want and copy the entire M code block

// 🔥 QUERY 1: Sales + Customers (Revenue by Customer Segment)
// Copy this entire block into PowerBI Advanced Editor:

let
    // Sales Revenue by Customer Segment - Auto-joins: Sales + Customers
    Source = Json.Document(
        Web.Contents(
            "http://localhost:4000/cubejs-api/v1/load",
            [
                Query = [
                    query = "{""measures"":[""Sales.totalRevenue"",""Sales.count"",""Customers.count"",""Customers.averageLifetimeValue""],""dimensions"":[""Customers.customerSegment"",""Sales.region""]}"
                ],
                Headers = [
                    Authorization = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.Et9HFtf9R3GEMA0IICOfFMVXY7kkTX1wr4qCyhIf58U"
                ]
            ]
        )
    ),
    ExtractData = Source[data],
    ConvertToTable = Table.FromRecords(ExtractData),
    ChangeTypes = Table.TransformColumnTypes(ConvertToTable,{
        {"Sales.totalRevenue", type number},
        {"Sales.count", Int64.Type},
        {"Customers.count", Int64.Type},
        {"Customers.averageLifetimeValue", type number}
    })
in
    ChangeTypes

// =================================================================

// 🚀 QUERY 2: Sales + Marketing (Campaign Performance Analysis)
// Copy this entire block into PowerBI Advanced Editor:

let
    // Sales Performance by Marketing Campaign - Auto-joins: Sales + Marketing
    Source = Json.Document(
        Web.Contents(
            "http://localhost:4000/cubejs-api/v1/load",
            [
                Query = [
                    query = "{""measures"":[""Sales.totalRevenue"",""Sales.count"",""Marketing.totalBudget"",""Marketing.totalAdSpend""],""dimensions"":[""Marketing.campaignType"",""Marketing.campaignName"",""Sales.region""]}"
                ],
                Headers = [
                    Authorization = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.Et9HFtf9R3GEMA0IICOfFMVXY7kkTX1wr4qCyhIf58U"
                ]
            ]
        )
    ),
    ExtractData = Source[data],
    ConvertToTable = Table.FromRecords(ExtractData),
    ChangeTypes = Table.TransformColumnTypes(ConvertToTable,{
        {"Sales.totalRevenue", type number},
        {"Sales.count", Int64.Type},
        {"Marketing.totalBudget", type number},
        {"Marketing.totalAdSpend", type number}
    })
in
    ChangeTypes

// =================================================================

// 🎯 QUERY 3: All 3 Tables (Complete Business Intelligence)
// Copy this entire block into PowerBI Advanced Editor:

let
    // Complete Business Intelligence - Auto-joins: Sales + Marketing + Customers
    Source = Json.Document(
        Web.Contents(
            "http://localhost:4000/cubejs-api/v1/load",
            [
                Query = [
                    query = "{""measures"":[""Sales.totalRevenue"",""Marketing.totalBudget"",""Customers.count"",""Marketing.activeCampaigns""],""dimensions"":[""Sales.region"",""Customers.customerSegment"",""Marketing.campaignType""]}"
                ],
                Headers = [
                    Authorization = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.Et9HFtf9R3GEMA0IICOfFMVXY7kkTX1wr4qCyhIf58U"
                ]
            ]
        )
    ),
    ExtractData = Source[data],
    ConvertToTable = Table.FromRecords(ExtractData),
    ChangeTypes = Table.TransformColumnTypes(ConvertToTable,{
        {"Sales.totalRevenue", type number},
        {"Marketing.totalBudget", type number},
        {"Customers.count", Int64.Type},
        {"Marketing.activeCampaigns", Int64.Type}
    })
in
    ChangeTypes

// =================================================================

// 🎯 QUERY 4: Marketing ROI by Customer Segment (Custom Query)
// Copy this entire block into PowerBI Advanced Editor:

let
    // Marketing ROI by Customer Segment - Auto-joins: Sales + Marketing + Customers
    Source = Json.Document(
        Web.Contents(
            "http://localhost:4000/cubejs-api/v1/load",
            [
                Query = [
                    query = "{""measures"":[""Sales.totalRevenue"",""Marketing.totalBudget"",""Marketing.totalAdSpend"",""Customers.count""],""dimensions"":[""Customers.customerSegment"",""Marketing.campaignType"",""Marketing.platform""]}"
                ],
                Headers = [
                    Authorization = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.Et9HFtf9R3GEMA0IICOfFMVXY7kkTX1wr4qCyhIf58U"
                ]
            ]
        )
    ),
    ExtractData = Source[data],
    ConvertToTable = Table.FromRecords(ExtractData),
    ChangeTypes = Table.TransformColumnTypes(ConvertToTable,{
        {"Sales.totalRevenue", type number},
        {"Marketing.totalBudget", type number},
        {"Marketing.totalAdSpend", type number},
        {"Customers.count", Int64.Type}
    }),
    // Add calculated ROI column
    AddROIColumn = Table.AddColumn(ChangeTypes, "ROI %", 
        each if [Marketing.totalAdSpend] <> null and [Marketing.totalAdSpend] > 0 
             then Number.Round(([Sales.totalRevenue] - [Marketing.totalAdSpend]) / [Marketing.totalAdSpend] * 100, 2)
             else null, 
        type number)
in
    AddROIColumn

// =================================================================
// 🔧 HOW TO USE:
// 
// 1. In PowerBI Desktop: Get Data → Blank Query
// 2. Home Tab → Advanced Editor  
// 3. Delete all existing code
// 4. Copy & Paste ONE of the M code blocks above
// 5. Click "Done"
// 6. Data will load with automatic joins! ✅
//
// ✨ The joins happen automatically - no manual relationships needed!
// 📊 You'll see columns from multiple tables joined seamlessly
// 
// 🎯 QUERY 4 includes bonus ROI calculation:
// ROI % = (Revenue - Ad Spend) / Ad Spend * 100